# Travis CI Java documentation can be found in:
# https://docs.travis-ci.com/user/languages/java/
language: java

os: osx

sudo: required

addons:
  homebrew:
    taps: homebrew/cask-versions
    packages:
      - botan
    update: true

cache:
  directories:
    - ~/.m2

jdk:
  - openjdk11

branches:
  only:
    - master

script: mvn clean verify
