name: Java CI

on: 
  push:
    branches:
    - master # build after merging code to master
    
  pull_request:
    branches:
    - master # build after opening a new PR
  
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC 

jobs:
  build:
    runs-on: [ubuntu:18.04, ubuntu:20.04]

    steps:
      - name: checkout repository code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      
      - name: Install botan
        run: sudo apt-get install -y botan

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
